
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class Login extends javax.swing.JFrame {
    public String userName;
    public String email;
    public String password;  
    
    public Login(String userName, String email, String password){
        this.userName = userName;
        this.email = email;
        this.password = password;
    }
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        buttonSignup2 = new javax.swing.JButton();
        pass_icon = new javax.swing.JLabel();
        welcome = new javax.swing.JLabel();
        user_icon = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        label_user = new javax.swing.JLabel();
        label_pass = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        userLogin = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        backLogin = new javax.swing.JButton();
        shoeOne = new javax.swing.JLabel();
        loginPass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        buttonLogin = new javax.swing.JButton();

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Shoeniverse");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel4.setBackground(new java.awt.Color(245, 245, 245));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonSignup2.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        buttonSignup2.setForeground(new java.awt.Color(164, 196, 181));
        buttonSignup2.setText("Sign Up");
        buttonSignup2.setBorder(null);
        buttonSignup2.setContentAreaFilled(false);
        buttonSignup2.setFocusable(false);
        buttonSignup2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonSignup2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonSignup2MouseExited(evt);
            }
        });
        buttonSignup2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSignup2ActionPerformed(evt);
            }
        });
        jPanel4.add(buttonSignup2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 490, 60, -1));

        pass_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/password.png"))); // NOI18N
        jPanel4.add(pass_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, -1, 70));

        welcome.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        welcome.setForeground(new java.awt.Color(51, 51, 51));
        welcome.setText(" Welcome to Shoeniverse!");
        jPanel4.add(welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, -1, -1));

        user_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user.png"))); // NOI18N
        jPanel4.add(user_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, -1, 70));

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Forgot Password?");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 390, 110, -1));

        label_user.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        label_user.setForeground(new java.awt.Color(51, 51, 51));
        label_user.setText("User name or Email");
        jPanel4.add(label_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, -1, -1));

        label_pass.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        label_pass.setForeground(new java.awt.Color(51, 51, 51));
        label_pass.setText("Password");
        jPanel4.add(label_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, -1, -1));

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("New to Shoeniverse?");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 490, -1, -1));

        userLogin.setBackground(new java.awt.Color(242, 242, 242));
        userLogin.setBorder(null);
        userLogin.setOpaque(false);
        jPanel4.add(userLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 280, 30));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, 280, 20));
        jPanel4.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, 280, -1));

        jPanel1.setBackground(new java.awt.Color(164, 196, 181));
        jPanel1.setPreferredSize(new java.awt.Dimension(450, 600));

        backLogin.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        backLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        backLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backLogin.setFocusable(false);
        backLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backLoginActionPerformed(evt);
            }
        });

        shoeOne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/shoeOne.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(shoeOne, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(shoeOne, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 600));

        loginPass.setBackground(new java.awt.Color(245, 245, 245));
        loginPass.setBorder(null);
        jPanel4.add(loginPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 280, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/shoeniverseLogo.png"))); // NOI18N
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, -1, -1));

        buttonLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login.png"))); // NOI18N
        buttonLogin.setContentAreaFilled(false);
        buttonLogin.setFocusable(false);
        buttonLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonLoginMouseExited(evt);
            }
        });
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });
        jPanel4.add(buttonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 430, 110, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(487, 487, 487)
                .addComponent(jLabel2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel2))
        );

        setSize(new java.awt.Dimension(914, 637));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSignup2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSignup2ActionPerformed
        this.dispose();
        new Signup().setVisible(true);
    }//GEN-LAST:event_buttonSignup2ActionPerformed

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) { 
        String userID= userLogin.getText().trim();
        String userPassword= String.valueOf(loginPass.getPassword()).trim();
        try {
            BufferedReader bufferReader = new BufferedReader(new FileReader("UserData.csv"));
            String[] values= bufferReader.readLine().split(",");
            if((userID.equals(values[0]) || userID.equals(values[1])) && userPassword.equals(values[2])){
                this.dispose();
                new ShoeStoreInfo().setVisible(true);

            }else{
            }
        } catch (FileNotFoundException ex) {
           JOptionPane.showMessageDialog(this, "File not Found");
        }catch(IOException ex){
            JOptionPane.showMessageDialog(this, "IOException occured.");
        }
    }

    private void buttonLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLoginMouseEntered
        // TODO add your handling code here:
        buttonLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/loginTwo.png")));
    }//GEN-LAST:event_buttonLoginMouseEntered

    private void buttonLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLoginMouseExited
        // TODO add your handling code here:
        buttonLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login.png")));
    }//GEN-LAST:event_buttonLoginMouseExited

    private void buttonSignup2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSignup2MouseEntered
        // TODO add your handling code here:
        buttonSignup2.setForeground(new java.awt.Color(124, 190, 159));
    }//GEN-LAST:event_buttonSignup2MouseEntered

    private void buttonSignup2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSignup2MouseExited
        // TODO add your handling code here:
        buttonSignup2.setForeground(new java.awt.Color(164, 196, 181));
    }//GEN-LAST:event_buttonSignup2MouseExited

    private void backLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backLoginActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Signup().setVisible(true);
    }//GEN-LAST:event_backLoginActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backLogin;
    private javax.swing.JButton buttonLogin;
    private javax.swing.JButton buttonSignup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel label_pass;
    private javax.swing.JLabel label_user;
    private javax.swing.JPasswordField loginPass;
    private javax.swing.JLabel pass_icon;
    private javax.swing.JLabel shoeOne;
    private javax.swing.JTextField userLogin;
    private javax.swing.JLabel user_icon;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
