/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Acer
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage1
     */
    public MainPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        partners = new javax.swing.JLabel();
        shoeAd = new javax.swing.JLabel();
        mainLogin = new javax.swing.JButton();
        mainSignup = new javax.swing.JButton();
        sloganTwo = new javax.swing.JLabel();
        footer = new javax.swing.JLabel();
        slogan = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(246, 243, 243));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        partners.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        partners.setForeground(new java.awt.Color(51, 51, 51));
        partners.setText("Our Brand Partners");
        jPanel1.add(partners, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 650, 190, 30));

        shoeAd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/shoeAd.gif"))); // NOI18N
        jPanel1.add(shoeAd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 590, 620));

        mainLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mainLogin.png"))); // NOI18N
        mainLogin.setContentAreaFilled(false);
        mainLogin.setFocusable(false);
        mainLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mainLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mainLoginMouseExited(evt);
            }
        });
        mainLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainLoginActionPerformed(evt);
            }
        });
        jPanel1.add(mainLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 110, 290, 60));

        mainSignup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mainSignup.png"))); // NOI18N
        mainSignup.setContentAreaFilled(false);
        mainSignup.setFocusPainted(false);
        mainSignup.setFocusable(false);
        mainSignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mainSignupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mainSignupMouseExited(evt);
            }
        });
        mainSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainSignupActionPerformed(evt);
            }
        });
        jPanel1.add(mainSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 200, 290, 60));

        sloganTwo.setFont(new java.awt.Font("Malayalam MN", 1, 36)); // NOI18N
        sloganTwo.setForeground(new java.awt.Color(51, 51, 51));
        sloganTwo.setText("YOUR FINGER TIPS\"");
        jPanel1.add(sloganTwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(703, 452, 367, 60));

        footer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/brandPartners.png"))); // NOI18N
        jPanel1.add(footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 689, -1, 70));

        slogan.setFont(new java.awt.Font("Malayalam MN", 1, 36)); // NOI18N
        slogan.setForeground(new java.awt.Color(51, 51, 51));
        slogan.setText("\"BEST SHOES AT");
        jPanel1.add(slogan, new org.netbeans.lib.awtextra.AbsoluteConstraints(644, 376, 315, 70));

        mainPanel.setBackground(new java.awt.Color(164, 196, 181));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/shoeniverseLogo.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconMainPage.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 654, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(41, 41, 41))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jPanel1.add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1097, 787));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mainLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainLoginMouseEntered
        // TODO add your handling code here:
        mainLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mainLogin2.png")));
    }//GEN-LAST:event_mainLoginMouseEntered

    private void mainLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainLoginMouseExited
        // TODO add your handling code here:
        mainLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mainLogin.png")));
    }//GEN-LAST:event_mainLoginMouseExited

    private void mainLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainLoginActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_mainLoginActionPerformed

    private void mainSignupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainSignupMouseEntered
        // TODO add your handling code here:
        mainSignup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mainSignup2.png")));
    }//GEN-LAST:event_mainSignupMouseEntered

    private void mainSignupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainSignupMouseExited
        // TODO add your handling code here:
        mainSignup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mainSignup.png")));
    }//GEN-LAST:event_mainSignupMouseExited

    private void mainSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainSignupActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Signup().setVisible(true);
    }//GEN-LAST:event_mainSignupActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        

    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel footer;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JButton mainLogin;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton mainSignup;
    private javax.swing.JLabel partners;
    private javax.swing.JLabel shoeAd;
    private javax.swing.JLabel slogan;
    private javax.swing.JLabel sloganTwo;
    // End of variables declaration//GEN-END:variables
}
