

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class ShoeStoreInfo extends javax.swing.JFrame {

    /**
     * Creates new form ShoeStoreInfo
     */
    public ShoeStoreInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        addShoe = new javax.swing.JButton();
        searchShoe = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Shoeniverse");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));

        jPanel2.setBackground(new java.awt.Color(241, 241, 241));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(164, 196, 181));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/shoeniverseLogo.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iconMainPage.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 518, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(37, 37, 37))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );

        jPanel2.add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 80));

        addShoe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/addShoe.png"))); // NOI18N
        addShoe.setContentAreaFilled(false);
        addShoe.setFocusable(false);
        addShoe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addShoeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addShoeMouseExited(evt);
            }
        });
        addShoe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addShoeActionPerformed(evt);
            }
        });
        jPanel2.add(addShoe, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 290, 60));

        searchShoe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/searchShoe.png"))); // NOI18N
        searchShoe.setContentAreaFilled(false);
        searchShoe.setFocusable(false);
        searchShoe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchShoeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchShoeMouseExited(evt);
            }
        });
        searchShoe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchShoeActionPerformed(evt);
            }
        });
        jPanel2.add(searchShoe, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 290, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Hnet-image (1).gif"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 960, 580));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(974, 696));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchShoeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchShoeMouseEntered
        // TODO add your handling code here:
        searchShoe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/searchShoe2.png")));
    }//GEN-LAST:event_searchShoeMouseEntered

    private void searchShoeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchShoeMouseExited
        // TODO add your handling code here:
        searchShoe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/searchShoe.png")));
    }//GEN-LAST:event_searchShoeMouseExited

    private void searchShoeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchShoeActionPerformed
        this.dispose();
        new SearchShoe().setVisible(true);
    }//GEN-LAST:event_searchShoeActionPerformed

    private void addShoeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addShoeActionPerformed
        this.dispose();
        new AddShoe().setVisible(true);
    }//GEN-LAST:event_addShoeActionPerformed

    private void addShoeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addShoeMouseEntered
        // TODO add your handling code here:
        addShoe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/addShoe2.png")));
    }//GEN-LAST:event_addShoeMouseEntered

    private void addShoeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addShoeMouseExited
        // TODO add your handling code here:
        addShoe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/addShoe.png")));
    }//GEN-LAST:event_addShoeMouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.dispose();
        new MainPage().setVisible(true);
       
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShoeStoreInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShoeStoreInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShoeStoreInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShoeStoreInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShoeStoreInfo().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addShoe;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton searchShoe;
    // End of variables declaration//GEN-END:variables
}
