import java.awt.Color;
import java.io.File;
import java.io.FileWriter;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form Sign up
     */
    public Signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        signupEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        shoeOne = new javax.swing.JLabel();
        backSignup = new javax.swing.JButton();
        createAccount = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        label_username = new javax.swing.JLabel();
        signupCheckbox = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        bottonLogin2 = new javax.swing.JButton();
        signupUser = new javax.swing.JTextField();
        label_email = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        label_password = new javax.swing.JLabel();
        signupPass = new javax.swing.JPasswordField();
        buttonSignup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Shoeniverse");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(245, 245, 245));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText(" .");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 430, 70, 20));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user.png"))); // NOI18N
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 60, 70));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 280, -1));

        signupEmail.setBackground(new java.awt.Color(245, 245, 245));
        signupEmail.setBorder(null);
        signupEmail.setOpaque(false);
        signupEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                signupEmailFocusLost(evt);
            }
        });
        jPanel2.add(signupEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, 280, 30));

        jLabel9.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(164, 196, 181));
        jLabel9.setText("Privacy Policy");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 430, -1, 20));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/email.png"))); // NOI18N
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 60, 70));

        jLabel10.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(164, 196, 181));
        jLabel10.setText(" Terms of Use");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 430, 90, 20));

        jPanel1.setBackground(new java.awt.Color(164, 196, 181));
        jPanel1.setPreferredSize(new java.awt.Dimension(450, 600));

        shoeOne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/shoeOne.png"))); // NOI18N

        backSignup.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        backSignup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        backSignup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backSignup.setFocusable(false);
        backSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backSignupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(shoeOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(shoeOne, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 600));

        createAccount.setFont(new java.awt.Font("Vogue", 1, 36)); // NOI18N
        createAccount.setForeground(new java.awt.Color(51, 51, 51));
        createAccount.setText("Create Account");
        jPanel2.add(createAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, -1, -1));

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Already a member?");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 530, -1, -1));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 280, -1));

        label_username.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        label_username.setForeground(new java.awt.Color(51, 51, 51));
        label_username.setText("User name");
        jPanel2.add(label_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, -1, -1));

        signupCheckbox.setBackground(new java.awt.Color(245, 245, 245));
        signupCheckbox.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        signupCheckbox.setForeground(new java.awt.Color(51, 51, 51));
        signupCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupCheckboxActionPerformed(evt);
            }
        });
        jPanel2.add(signupCheckbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, 20, 40));

        jLabel11.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("  &");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 430, -1, 20));

        bottonLogin2.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        bottonLogin2.setForeground(new java.awt.Color(164, 196, 181));
        bottonLogin2.setText("Login Here");
        bottonLogin2.setBorder(null);
        bottonLogin2.setContentAreaFilled(false);
        bottonLogin2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bottonLogin2.setFocusable(false);
        bottonLogin2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bottonLogin2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bottonLogin2MouseExited(evt);
            }
        });
        bottonLogin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonLogin2ActionPerformed(evt);
            }
        });
        jPanel2.add(bottonLogin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 530, 90, -1));

        signupUser.setBackground(new java.awt.Color(245, 245, 245));
        signupUser.setBorder(null);
        signupUser.setOpaque(false);
        signupUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupUserActionPerformed(evt);
            }
        });
        jPanel2.add(signupUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, 280, 30));

        label_email.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        label_email.setForeground(new java.awt.Color(51, 51, 51));
        label_email.setText("Email");
        jPanel2.add(label_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, -1, -1));

        jLabel7.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("I accept the");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, -1, 20));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/password.png"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 60, 70));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 280, 10));

        label_password.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        label_password.setForeground(new java.awt.Color(51, 51, 51));
        label_password.setText("Password");
        jPanel2.add(label_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, -1, -1));

        signupPass.setBackground(new java.awt.Color(245, 245, 245));
        signupPass.setBorder(null);
        jPanel2.add(signupPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 370, 285, 30));

        buttonSignup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/signup.png"))); // NOI18N
        buttonSignup.setContentAreaFilled(false);
        buttonSignup.setEnabled(false);
        buttonSignup.setFocusable(false);
        buttonSignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonSignupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonSignupMouseExited(evt);
            }
        });
        buttonSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSignupActionPerformed(evt);
            }
        });
        jPanel2.add(buttonSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 470, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signupCheckboxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_signupCheckboxActionPerformed
        if(signupCheckbox.isSelected()){
            buttonSignup.setEnabled(true);
        }else if (!signupCheckbox.isSelected()){
            buttonSignup.setEnabled(false);
        }
    }// GEN-LAST:event_signupCheckboxActionPerformed

    private void bottonLogin2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bottonLogin2ActionPerformed
        this.dispose();
        new Login().setVisible(true);
    }// GEN-LAST:event_bottonLogin2ActionPerformed

    private void signupUserActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_signupUserActionPerformed
    }// GEN-LAST:event_signupUserActionPerformed

    private void buttonSignupMouseEntered(java.awt.event.MouseEvent evt) {
        buttonSignup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/signupTwo.png")));
    }

    private void buttonSignupMouseExited(java.awt.event.MouseEvent evt) {
        buttonSignup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/signup.png")));
    }

    private void bottonLogin2MouseEntered(java.awt.event.MouseEvent evt) {
        bottonLogin2.setForeground(new java.awt.Color(124, 190, 159));
    }

    private void bottonLogin2MouseExited(java.awt.event.MouseEvent evt) {
        bottonLogin2.setForeground(new java.awt.Color(164, 196, 181));
    }

    private void buttonSignupActionPerformed(java.awt.event.ActionEvent evt) {
        String email = signupEmail.getText().trim();
        String userName = signupUser.getText().trim();
        String password = String.valueOf(signupPass.getPassword()).trim();
        String[] userData = {userName, email, password};
        writeData(userData);
        this.dispose();
        new Login().setVisible(true);
    }

    private void backSignupActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();
        new MainPage().setVisible(true);
    }

    private void signupEmailFocusLost(java.awt.event.FocusEvent evt) {
        if (signupEmail.getText().matches("^[A-Za-z0-9+_.-]+@(.+)$")) {
            signupEmail.setForeground(Color.black);
        } else {
            signupEmail.setText(signupEmail.getText());
            signupEmail.setForeground(new java.awt.Color(255, 0, 0));
        }
    }
    
    public void writeData(String values[]){
         FileWriter fileWriter = null;
        try {
            File file = new File("UserData.csv");
            if (!file.isFile()) {
                file.createNewFile();
            }
            fileWriter = new FileWriter(file);
            for (int i = 0; i < values.length; i++) {
                fileWriter.append(values[i]);
                if( i == values.length-1){
                    break;
                }
                fileWriter.append(",");
            }
        fileWriter.flush();
        fileWriter.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No file found");
        }
    
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Signup().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backSignup;
    private javax.swing.JButton bottonLogin2;
    private javax.swing.JButton buttonSignup;
    private javax.swing.JLabel createAccount;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel label_email;
    private javax.swing.JLabel label_password;
    private javax.swing.JLabel label_username;
    private javax.swing.JLabel shoeOne;
    private javax.swing.JCheckBox signupCheckbox;
    private javax.swing.JTextField signupEmail;
    private javax.swing.JPasswordField signupPass;
    private javax.swing.JTextField signupUser;
    // End of variables declaration//GEN-END:variables
}
